name: linter

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  format:
    if: ${{ github.actor != 'dependabot' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - name: Prettier
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,tsx,jsx,css,scss}
        only_changed: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Linter
      uses: tj-actions/eslint-changed-files@v4
      with:
        config-path: '.eslintrc.js'
        ignore-path: '.eslintignore'
        extensions: 'ts,tsx,js,jsx'
